# Generated by Django 3.1.5 on 2021-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribute',
            name='Readed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
