# Generated by Django 3.1.5 on 2021-02-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20210208_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='ClosureDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='FinalClosureDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
