# Generated by Django 3.1.4 on 2021-03-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20210313_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Contribute',
            new_name='ContributeID',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='UserID',
        ),
    ]
