# Generated by Django 3.1.5 on 2021-03-01 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_user_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameContribute', models.CharField(max_length=20)),
                ('DateContribute', models.DateTimeField()),
                ('Status', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('idTerm', models.AutoField(primary_key=True, serialize=False)),
                ('NameTerm', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('ClosureDate', models.DateTimeField()),
                ('FinalClosureDate', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ClosureDate',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='FinalClosureDate',
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('idData', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.FileField(upload_to='')),
                ('Contribute', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.contribute')),
            ],
        ),
        migrations.AddField(
            model_name='contribute',
            name='Term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.term'),
        ),
        migrations.AddField(
            model_name='contribute',
            name='User',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
