# Generated by Django 3.1.5 on 2021-03-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
