# Generated by Django 3.1.5 on 2021-03-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Data',
            field=models.FileField(upload_to='FileData/'),
        ),
    ]
