# Generated by Django 3.1.5 on 2021-02-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20210222_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.faculty'),
        ),
    ]
